---
title: "Multinatinal Bank Customer Churn"
output: 
  html_document:
    theme: "spacelab"
    highlight: kate
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 6
    toc_float: yes
    collapsed: false
    smooth_scroll: false
  pdf_document:
    toc: yes
    toc_depth: '3'

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Chapter 1: Introduction

Customer churn, also known as customer turnover, occurs when a customer chooses to leave or unsubscribe from a service for any reason. In the context of this project, we are looking at customer churn in banking. Being able to predict customer churn is important because we want to retain as many customers as we can. Of course you want to keep customers, but it also is cheaper to retain your customers, than having to spend money to acquire new customers to replace the ones that left. Lower customer acquisition costs equal more profits. By identifying customers at risk of churn, we are able to identify which efforts in order to maximize their likelihood of staying. 

In our research, we aim, through EDA, to identify the variables which have the highest correlation with churn, across three countries serviced by a multinational bank. The variables identified can then be used to inform banks of what customer activity trends and attributes should be monitored so the bank can make efforts to retain the customers before the account has been closed.

This report is organized as follows:

# Choosing the Topic

We chose to analyze a multinational bank’s churn for several reasons. As an international team, we were interested in topics that spanned multiple countries, with a particular focus on either business or environment, our personal interests. When we were pitching topics, nearly every suggestion was geared towards sales or customer experience, or global environmental issues. After ensuring that the data sets that interested us had enough observations to follow the project’s guidelines, we then identified the topics with the highest number of useful variables. There were several data sets, which, while interesting, did not yield enough useful variables. Rather, they included variables like unique product, user, or review identifiers, which were not relevant to the type of analysis we were performing. From our short-list, the Bank Customer Churn Data Set had the highest number of useful variables, 11 out of the 12, as opposed to 4-6 useful variables for our runner-up options. We made the decision to go with our chosen data set because we figured that a larger number of variables (and data) is a closer reflection of the multitude of factors that affect a customer’s decision to churn. Additionally, we do not know at first glance which of the variables will end up being statistically significant, however, by having a higher number of variables, we are considering the potential effects of a wider range of variables, which may be useful to our model after we perform EDA.

After finding a data set that piqued our personal interests, met the project requirements, and had a larger range of variables than the other top choices, we were satisfied with our choice and able to proceed to the next stage.


# Chapter 2: Description of the data


A limitation of the data set is that it is imbalanced, as the customer country is not evenly distributed. There are three countries, however half of all customers are based in France, and the remaining two countries are each home to a quarter of all customers.
When creating our model, we will need to take this into account and plan to handle this imbalanced data. A second limitation is that some of the variables are poorly defined. One such variable is ‘active_member’, which does not operationally define what it means to be an active member (ie. has not logged in in X months, has had no deposits in time period X). Another variable which does not provide enough information about its definition is Products Number. While it does give the number of products, we do not know which products, and in which combination they are used by the customers. While we can draw conclusions based on the number of products, we cannot make further inferences about the type of product or combinations of products.


## 
